site_name: FRISP User Documentation
theme: readthedocs
nav:
  - 'index.md'
  - 'Cloud':
      - 'Creating App Passwords': 'cloud/app-password-creation.md'
  - 'Single Sign-On':
      - 'Introduction': 'sso/index.md'
